### ISSUE TITLE
Error (Xcode): Unable to load contents of file list: '/Target Support Files/Pods-Runner/Pods-Runner-frameworks-Release-<flavorName>-output-files.xcfilelist'

### ISSUE THREAD

**Issue by krekzsolti** [AngeloAvv/flutter_flavorizr#145]
Hi,

I am trying to build my app using flavorizr from bitrise.
The way I would like to do it, that the project from git would be cloned without any flavour, I would like to create the flavours from bitrise.

Now I get this error: 

Error (Xcode): Unable to load contents of file list: '/Target Support Files/Pods-Runner/Pods-Runner-frameworks-Release-szikra-input-files.xcfilelist'
Error (Xcode): Unable to load contents of file list: '/Target Support Files/Pods-Runner/Pods-Runner-frameworks-Release-szikra-output-files.xcfilelist'

I saw some issues filed of this error, but since this flavorizing process is done on bitrise, I can't really edit the pod file-s manually.
I tried downgrading the target platform to 12.0, but didn't work.

Does anyone has any solutions?

**Comment by SirawichDev** [comment]
me too

**Comment by guildem** [comment]
Same issue here.

I tried to add manually the `Debug-{flavor}`, `Profile-{flavor}`, `Release-{flavor}` lines (for each flavor) on the Podfile line 7 array. This allows to build the 'missing' files but nothing is fixed. If someone has a workaround, even hacky, i'll take it !

**Comment by madoka3530** [comment]
Same error

**Comment by mhmzdev** [comment]
Anything on this yet?

**Comment by gukong** [comment]
This answer (https://stackoverflow.com/a/56966495/5496410) saved my life.

**Comment by AngeloAvv** [comment]
Hi @krekzsolti , what's the difference between your project and the example project?
Is there a way to make this problem deterministic?

**Comment by mobikats** [comment]
> This answer (https://stackoverflow.com/a/56966495/5496410) saved my life.

Unfortunately I end up with 
<img width="695" alt="Screenshot 2023-06-15 at 14 26 12" src="https://github.com/AngeloAvv/flutter_flavorizr/assets/5747434/5d81b87a-bb07-4149-9073-da8d2af3ca45">

**Comment by AngeloAvv** [comment]
Delete your Podfile.lock, delete the Pods and .symlinks folders, and run pub get again. This will solve the issue.

**Comment by mhmzdev** [comment]
For me, it was resolved after upgrading to latest flutter version and upgrading the pods to latest (y)

**Comment by iKK001** [comment]
I still have this issue.

None of the above worked. I am totally miserable.
